### PR TITLE
Change func to fun

### PR DESCRIPTION
**Pull request by Zandra7**

### CODE REVIEW

**Comment by Lucas8448** [comment]
but why?

**Comment by Zandra7** [comment]
Changing func to fun might make the code more readable or consistent with other programming languages that use fun.

**Comment by Lucas8448** [comment]
Hey,

I get the appeal of using "fun" for function declarations—it's catchy and a bit unique. But there are some compelling reasons for sticking with the more traditional "func":

    Familiarity: A lot of existing languages like Swift, Go, and TypeScript use "func." Developers coming from these backgrounds will find it easier to adapt to our new language.

    Clarity: While "fun" is cool, "func" more explicitly suggests that we're dealing with a function. It's a tiny detail but could reduce cognitive load when scanning through code.

    Professionalism: "func" has a more formal and technical feel, which might make the language more appealing for serious or enterprise-level applications.

    Tooling: By using a more standard keyword, we might have an easier time integrating with existing IDEs, linters, and other developer tools.

    Documentation and Learning Resources: If we go with "func," there's a higher chance that new learners can leverage existing tutorials, articles, and videos focused on other languages that use the same keyword. This can make the learning curve a bit less steep.

    Portability and Interoperability: If we ever want our language to easily interface with existing languages, libraries, or frameworks, using a more universally recognized keyword like "func" could smooth out the process.

    Community Expectations: Deviating from common conventions can be a hit or miss. If we don't have a compelling reason for the change, sticking to what people already know can be a safer bet.

**Comment by Zandra7** [comment]
Hey,

I get where you're coming from, especially on the familiarity and clarity fronts. However, I'd like to present some counter-arguments for why I think "fun" could be a better fit for your new language:

1. Simplicity: `fun` is not only shorter but also easier to type. This could streamline the coding process, making your language more user-friendly.

2. Innovation: The keyword `fun` could help set our language apart, making it memorable. Sometimes a small twist can have a big impact on how a language is perceived.

3. Readability: Languages like Kotlin have shown that shorter keywords can actually improve readability. `fun` captures the essence of a function without being verbose.

4. Modern Trends: Some of the newer languages are opting for more intuitive, shorter syntax. If you aim for your language to be modern and forward-thinking, then following this trend makes sense.

5. Ease of Learning: Shorter and more intuitive keywords could make your language easier for beginners. The learning curve might not be as steep.

6. Faster Coding: Less typing means faster coding, which could be particularly beneficial in scenarios requiring rapid development.

I think these points could make "fun" a viable, if not preferable, choice for your language. Looking forward to hearing your thoughts!

**Comment by Lucas8448** [comment]
Ok da :)

**Pull request merged**
